### ISSUE TITLE
IMOD defocus file not recognised

### ISSUE THREAD

**Issue by andreanans** [turonova/novaCTF#1] opened 2017-08-14 17:22 UTC
Hi,

I estimated the defocus from each tilt image and have a file that looks like this:
For some reason it's not accepting this file even though it's directly from IMOD. I had to invert the tilt angles since the hand is inverted. Any ideas why this isn't working?

Thank you,

Andrea

38      38      -56.35  -56.35    9744   2
37      37      -53.18  -53.18    9813
36      36      -50.01  -50.01    9914
35      35      -46.85  -46.85    9809
34      34      -43.80  -43.80    9863
33      33      -40.76  -40.76    9855
32      32      -37.71  -37.71    9841
31      31      -34.67  -34.67    9822
30      30      -31.60  -31.60    9859
29      29      -28.53  -28.53    9783
28      28      -25.47  -25.47    9751
27      27      -22.40  -22.40    9711
26      26      -19.33  -19.33    9772
25      25      -16.26  -16.26    9952
24      24      -13.44  -13.44    9932
23      23      -10.62  -10.62   10500
22      22      -7.79   -7.79    10504
21      21      -4.97   -4.97    10642
20      20      -2.16   -2.16    10895
19      19       0.99    0.99    10906
18      18       4.13    4.13    10668
17      17       7.28    7.28    10682
16      16      10.42   10.42    10607
15      15      13.57   13.57    10802
14      14      16.71   16.71    10390
13      13      19.78   19.78    10566
12      12      22.85   22.85    10546
11      11      25.92   25.92    10686
10      10      28.99   28.99    10542
9       9       32.05   32.05    10593
8       8       35.14   35.14    10615
7       7       38.22   38.22    10603
6       6       41.31   41.31    10520
5       5       44.41   44.41    10530
4       4       47.49   47.49    10108
3       3       50.71   50.71    10511
2       2       53.95   53.95    10413
1       1       56.17   56.17    10361

**Comment by turonova** [comment] 2017-08-21 15:45
Sorry for the late reply, I was on holiday.

Could you please send me the command you are using to run novaCTF (including all parameters stored in *.com file) and also the output error message?

I tried your input and it worked for me.

**Comment by andreanans** [comment] 2017-08-21 16:45
Hi there,

It seems like now I cannot even get it to recognise the IMOD stack file. Here is the error message:

Reading parameters... 
Parsing the following parameter file: setup_defocus.com
Ignoring following parameter: 
...done

Starting computation of defocus.

terminate called after throwing an instance of 'ExceptionFileOpen'
  what():  Following file could not be opened: Tet13.st 

Abort (core dumped)

Here is the setupdefocus.com:

# Command file to run novaCTF
Algorithm defocus
InputProjections Tet13.st 
FULLIMAGE 3838 3710
THICKNESS 250 
TILTFILE Tet13.tlt
SHIFT 0.0 0.0
CorrectionType phaseflip
DefocusFileFormat imod
DefocusFile defocus.txt
PixelSize 0.271
DefocusStep 15

**Comment by turonova** [comment] 2017-08-21 16:49
The program cannot find and open Tet13.st - is this file at the same folder as the defocus.txt? Either add path to this file(s) so the program can find them, or copy the novaCTF binaries to the folder with your files and run it from there.

**Comment by andreanans** [comment] 2017-08-21 16:57
The stack file was in the same directory as the defocus file and the nova binaries. However specifying the full path to the stack file allowed the first step to proceed. It has created many defocus_n.txt files. When running the second step, I'm getting this error:

Reading parameters... 
Parsing the following parameter file: setup_ctfCorrection.com
Unknown type of CTF correction: phaseflip 
Ignoring following parameter: 
Ignoring following parameter: 
...done

Starting CTF correction.

The defocus file does not correspond to the specification either of version 2 or 3 (see ctfphaseflip man page on IMOD webpage)!

Here is my .com file:

Algorithm ctfCorrection
InputProjections /frames2/andrean/Nova/Tet13.st
DefocusFile /frames2/andrean/Nova/defocus.txt_1
OutputFile /frames2/andrean/Nova/corrected_stack.st_1
TILTFILE /frames2/andrean/Nova/Tet13.tlt
CorrectionType phaseflip
DefocusFileFormat imod
PixelSize 0.271
AmplitudeContrast 0.07
Cs 2.7
Volt 300

**Comment by turonova** [comment] 2017-08-21 17:09
What system are you running it on and what version of gcc do you have? Normally, the path specification should not be necessary if your binaries are in the same folder. Also it seems that it cannot recognize "phaseflip" so something is definitely wrong with the string comparison.

If you open file defocus.txt_1 it should look the same as your input defocus.txt only with defocus values slightly different but the first line should again contain 6 values with the last one being 2. Is that so?

**Comment by andreanans** [comment] 2017-08-21 17:12
I'm running Centos 7.3 with gcc version 4.8.5. I checked defocus.txt_1 and the first line contains 6 values and the last line has 5 values. I'll paste it here:
38 38 -56.35 -56.35 10173 2 
37 37 -53.18 -53.18 10242 
36 36 -50.01 -50.01 10343 
35 35 -46.85 -46.85 10238 
34 34 -43.8 -43.8 10292 
33 33 -40.76 -40.76 10284 
32 32 -37.71 -37.71 10270 
31 31 -34.67 -34.67 10251 
30 30 -31.6 -31.6 10288 
29 29 -28.53 -28.53 10212 
28 28 -25.47 -25.47 10180 
27 27 -22.4 -22.4 10140 
26 26 -19.33 -19.33 10201 
25 25 -16.26 -16.26 10381 
24 24 -13.44 -13.44 10361 
23 23 -10.62 -10.62 10929 
22 22 -7.79 -7.79 10933 
21 21 -4.97 -4.97 11071 
20 20 -2.16 -2.16 11324 
19 19 0.99 0.99 11335 
18 18 4.13 4.13 11097 
17 17 7.28 7.28 11111 
16 16 10.42 10.42 11036 
15 15 13.57 13.57 11231 
14 14 16.71 16.71 10819 
13 13 19.78 19.78 10995 
12 12 22.85 22.85 10975 
11 11 25.92 25.92 11115 
10 10 28.99 28.99 10971 
9 9 32.05 32.05 11022 
8 8 35.14 35.14 11044 
7 7 38.22 38.22 11032 
6 6 41.31 41.31 10949 
5 5 44.41 44.41 10959 
4 4 47.49 47.49 10537 
3 3 50.71 50.71 10940 
2 2 53.95 53.95 10842 
1 1 56.17 56.17 10790

**Comment by turonova** [comment] 2017-08-21 17:25
I'm afraid that this issue lies in the older version of your compiler (at least based on quick internet search). Could you try to replace -std=c++0x with -std=c++11 in the makefile and then run make again (after cleaning the binaries with "make clean" command)? It might not compile at all but it is worth a try.

If the recompiling does not help (or work), than try to update at least on GCC 4.9. I have tested it on 4.9.4 and 5.4.0 on CentOs7 and you should not have such problems there.

**Comment by andreanans** [comment] 2017-08-21 17:31
I recompiled novaCTF and step 1 works without having to specify the full path. I'm still getting the same error with step2 and the unknown type of ctf correction. I'll try to upgrade to gcc 4.9 and will let you know how it goes. Thanks for all your help so far.

**Comment by turonova** [comment] 2017-08-21 17:37
There is one more thing that can be quickly tested: since we know that the defocus.txt file worked in the step1, you can try to use it also in step2 - the reading routine is the same for both, so if it worked in the first one, it should work also in the second one. If not than the problem for sure lies in the compilation.

**Comment by andreanans** [comment] 2017-08-21 17:46
I copied defocus.txt to defocus_1.txt and it seems to finish and I get an output stack full. However I still get the error about the type of CTF correction. I don't see any difference between these text files so I'm not sure why it doesn't work with the original _1.txt files.

Reading parameters... 
Parsing the following parameter file: setup_ctfCorrection.com
Unknown type of CTF correction: phaseflip 
Ignoring following parameter: 
Ignoring following parameter: 
...done
Starting CTF correction.
CTF correction finished successfully!

**Comment by andreanans** [comment] 2017-08-21 17:55
OK think I figured it out. There is an extra blank space after each line in the _1.txt _2.txt defocus files produced by step 1 of novaCTF. There was also a blank space after phaseflip option in my com file which was causing the error message. After removing the extra spaces step 2 proceeds as normal. 
Is step 1 supposed to produce a defocus file with an extra space at the end of each line? It willl be a bit of a pain to remove them from each file.

Thanks

**Comment by turonova** [comment] 2017-08-21 18:13
No, there should not be any spaces at the end of lines and also command parsing should handle the empty spaces around parameters so something is still not working properly. I will look into this tomorrow and try to reproduce this weird behavior.

**Comment by turonova** [comment] 2017-08-22 11:38
I was able to reproduce the errors you are getting. The new version here should not add the spaces in the end of defocus files and also additional spaces in the *.com files should be ignored. Please let me know if it now works for you without any additional space removal from your side.

**Comment by andreanans** [comment] 2017-08-22 14:59
Hi,

I configured the new version but am still getting this error. It seems like it can't find the stack even though it is there and I specify the full path. Adjusting the makefile according to your suggestion from yesterday does not fix the problem either.

Reading parameters... 
Parsing the following parameter file: setup_defocus.com
...done

Starting computation of defocus.

terminate called after throwing an instance of 'ExceptionFileOpen'
  what():  Following file could not be opened: /frames2/andrean/Nova/Tet13.st 

Abort (core dumped)

**Comment by turonova** [comment] 2017-08-22 15:18
I think there is one more space at the end of your Tet13.st (I skipped the file input names handling for some reason) - I've just uploaded the fix for the file names here. Please download and try it.

**Comment by turonova** [comment] 2017-08-22 15:25
I noticed one last file name that was not properly handled for empty spaces and have uploaded the fix here just now.

**Comment by andreanans** [comment] 2017-08-23 11:40
Both steps work now with no problems. I didn't have to compile it with any special options. Thanks very much for that. I'll try to do the other steps to make sure the entire pipeline works. Quick question, since my tilt angles are inverted due to the hand being flipped what is the proper convention for the defocus files and the tilt angle file?

Is it ok to have a defocus file that lists the images in reverse order (ie 38 to 1) but have my tilt angles file list the angles from in order from 1-38? Each projection would be assigned to the same angle.

Thanks

**Comment by turonova** [comment] 2017-08-23 12:15
Great! I am glad it is working now.

For your question: the tilt angles in the defocus file are irrelevant for the algorithm (we do not need any tilt angle for CTF correction and also CTFFind4 does not take angles into account so the output file from it does not contain any tilt angle information) - we expect the lines to correspond to you sorted stack, i.e. the first line in your defocus file should correspond to the first image in your input stack. This holds also for tilt angle file - the first line will be assigned to the first image in your input stack. So for your case: if the first angle in your tilt file correspond to the first projection in your stack and the first line of your defocus file also correspond to the first projection, you do not have to worry about the numbers in the defocus file (only defocus is used not the first four numbers). If the first line of the defocus line corresponds to the LAST projection in your input stack than you have to revert the order in the defocus file.

**Comment by andreanans** [comment] 2017-08-23 13:27
Great thanks for the clarification!
All the best,
Andrea

**Closed as completed** 2017-08-29 09:24 UTC
